packages:
  - 'packages/*'

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@hono/node-server@2.0.10'
  - '@aws-sdk/client-s3@3.1126.0 || 3.1130.0'
  - '@aws-sdk/s3-request-presigner@3.1126.0 || 3.1130.0'
  - resend@6.26.0
  - tsdown@0.23.0
  - zod@4.6.2
